const ZURI_DATA = {
  countries: [
    { id: "us", name: "United States" },
    { id: "rw", name: "Rwanda" }
  ],
  cities: [
    {
      id: "omaha",
      name: "Omaha",
      country: "United States",
      isActive: true,
      tagline: "Friendly neighborhoods, serious food, rich culture, and easygoing days."
    },
    {
      id: "kigali",
      name: "Kigali",
      country: "Rwanda",
      isActive: false,
      tagline: "Future ZURI expansion market."
    }
  ],
  areas: [
    "Blackstone",
    "Benson",
    "Old Market",
    "Downtown",
    "Midtown",
    "Dundee",
    "Aksarben",
    "Little Bohemia",
    "Riverfront",
    "West Omaha",
    "South Omaha",
    "North Omaha"
  ],
  categories: [
    "Food",
    "Coffee",
    "Nightlife",
    "Culture",
    "Tours",
    "Outdoor/Nature",
    "Shopping",
    "Wellness",
    "Hotels",
    "Transportation",
    "Events",
    "Family Friendly",
    "Date Night",
    "Ask ZURI"
  ],
  moods: [
    "Easy",
    "Curious",
    "Social",
    "Romantic",
    "Family",
    "Active",
    "Indulgent",
    "Local"
  ],
  listings: [
    {
      id: "old-market-walk",
      title: "Old Market First-Timer Walk",
      country: "United States",
      city: "Omaha",
      area: "Old Market",
      category: "Tours",
      mood: ["Easy", "Curious", "Local"],
      shortDescription: "A low-pressure intro to Omaha with brick streets, galleries, patios, and easy browsing.",
      longDescription: "Start with a slow walk through Old Market, then browse a shop or gallery before choosing a nearby patio, dessert stop, or casual dinner. It works especially well when someone has just arrived and wants the city to feel manageable fast.",
      tags: ["first time", "walkable", "historic", "shops", "patios"],
      priceLevel: "$",
      estimatedDuration: "60-90 minutes",
      bestFor: "Visitors who want the classic Omaha starting point without overplanning.",
      trustSignal: "Reliable first stop because the area is compact, recognizable, and easy to navigate.",
      whyZuriRecommendsIt: "It gives you a quick sense of place and leaves room to pivot into food, shopping, or nightlife.",
      ctaLabel: "Ask ZURI to build around this"
    },
    {
      id: "block-16-lunch",
      title: "Block 16 Lunch Run",
      country: "United States",
      city: "Omaha",
      area: "Downtown",
      category: "Food",
      mood: ["Indulgent", "Local", "Social"],
      shortDescription: "A beloved casual lunch stop for bold sandwiches, fries, and an energetic downtown crowd.",
      longDescription: "Block 16 is a strong pick when you want food that feels distinctly local, satisfying, and unfussy. Pair it with a downtown walk or a stop at the Gene Leahy Mall when the weather cooperates.",
      tags: ["lunch", "casual", "downtown", "sandwiches", "local favorite"],
      priceLevel: "$$",
      estimatedDuration: "45-75 minutes",
      bestFor: "Food-focused visitors, casual dates, and groups that want an Omaha staple.",
      trustSignal: "Commonly recommended by locals and visitors for a memorable casual meal.",
      whyZuriRecommendsIt: "It feels specific to Omaha without requiring a formal reservation or a huge time block.",
      ctaLabel: "Add this to my plan"
    },
    {
      id: "archetype-blackstone",
      title: "Archetype Coffee in Blackstone",
      country: "United States",
      city: "Omaha",
      area: "Blackstone",
      category: "Coffee",
      mood: ["Easy", "Curious", "Local"],
      shortDescription: "A polished coffee stop in one of Omaha's most useful food-and-drink neighborhoods.",
      longDescription: "Use Archetype as a calm reset, a work break, or the first stop before exploring Blackstone's restaurants and bars. It is a simple anchor when your day needs structure but not pressure.",
      tags: ["coffee", "remote work", "blackstone", "morning", "espresso"],
      priceLevel: "$",
      estimatedDuration: "30-60 minutes",
      bestFor: "Solo travelers, remote workers, and coffee people starting a flexible day.",
      trustSignal: "Strong local reputation for quality coffee and a dependable neighborhood location.",
      whyZuriRecommendsIt: "It anchors the day in an area with easy next moves for lunch, dinner, or drinks.",
      ctaLabel: "Plan from here"
    },
    {
      id: "mula-blackstone",
      title: "Mula Tacos and Tequila",
      country: "United States",
      city: "Omaha",
      area: "Blackstone",
      category: "Food",
      mood: ["Social", "Indulgent", "Romantic"],
      shortDescription: "A lively Blackstone pick for tacos, drinks, and an easy group dinner mood.",
      longDescription: "Mula works when the group wants something more animated than a quiet dinner but less complicated than a full night out. It is also well placed for a second stop in Blackstone.",
      tags: ["tacos", "tequila", "group", "dinner", "blackstone"],
      priceLevel: "$$",
      estimatedDuration: "75-120 minutes",
      bestFor: "Groups, casual dates, and visitors who want a social dinner area.",
      trustSignal: "Neighborhood fit is strong because Blackstone has several easy follow-up options.",
      whyZuriRecommendsIt: "It keeps the night flexible and lets you continue nearby without moving across town.",
      ctaLabel: "Build a night around this"
    },
    {
      id: "benson-night-out",
      title: "Benson Night Out",
      country: "United States",
      city: "Omaha",
      area: "Benson",
      category: "Nightlife",
      mood: ["Social", "Local", "Curious"],
      shortDescription: "A casual nightlife circuit with music, drinks, food, and a neighborhood feel.",
      longDescription: "Benson is a good bet when you want a night that can stay loose. Start with dinner, see what music is happening, then choose a bar or late-night bite based on the room's energy.",
      tags: ["bars", "music", "late night", "local", "walkable"],
      priceLevel: "$$",
      estimatedDuration: "2-4 hours",
      bestFor: "People who want a relaxed local night rather than a polished hotel-bar scene.",
      trustSignal: "Known locally as one of Omaha's easiest neighborhoods for a casual night out.",
      whyZuriRecommendsIt: "It offers several choices close together, so the plan can adapt as the night changes.",
      ctaLabel: "Ask ZURI for a Benson route"
    },
    {
      id: "joslyn-arts",
      title: "Joslyn Art Museum Afternoon",
      country: "United States",
      city: "Omaha",
      area: "Midtown",
      category: "Culture",
      mood: ["Curious", "Easy", "Romantic"],
      shortDescription: "A beautiful culture stop for art, architecture, and a quieter Omaha afternoon.",
      longDescription: "Joslyn fits a refined, slower-paced day. It pairs well with coffee before, a Midtown meal after, or a date-night dinner when you want the day to feel considered but not busy.",
      tags: ["museum", "art", "architecture", "quiet", "rainy day"],
      priceLevel: "$",
      estimatedDuration: "90-150 minutes",
      bestFor: "Culture seekers, couples, and visitors needing an indoor anchor.",
      trustSignal: "Major Omaha cultural institution with a strong sense of place.",
      whyZuriRecommendsIt: "It adds depth and beauty to an itinerary without demanding the whole day.",
      ctaLabel: "Pair this with dinner"
    },
    {
      id: "durham-museum",
      title: "The Durham Museum",
      country: "United States",
      city: "Omaha",
      area: "Downtown",
      category: "Culture",
      mood: ["Curious", "Family", "Easy"],
      shortDescription: "Omaha history inside a grand former train station, with exhibits that work for many ages.",
      longDescription: "The Durham Museum is a strong indoor pick for history, architecture, and families. It can stand alone or pair with Old Market before or after because the move between them is simple.",
      tags: ["history", "museum", "family", "indoor", "architecture"],
      priceLevel: "$$",
      estimatedDuration: "90-150 minutes",
      bestFor: "Families, history fans, and visitors seeking an easy indoor activity.",
      trustSignal: "A recognized Omaha landmark with broad appeal across age groups.",
      whyZuriRecommendsIt: "It makes Omaha's story tangible and is easy to combine with downtown plans.",
      ctaLabel: "Add to a family plan"
    },
    {
      id: "gene-leahy-mall",
      title: "Gene Leahy Mall Reset",
      country: "United States",
      city: "Omaha",
      area: "Riverfront",
      category: "Outdoor/Nature",
      mood: ["Easy", "Family", "Active"],
      shortDescription: "A clean, central outdoor pause with green space, public art, and skyline views.",
      longDescription: "Gene Leahy Mall is useful when you want something free, easy, and close to downtown food. It is also a good transition stop between a museum, lunch, and the riverfront.",
      tags: ["park", "free", "downtown", "riverfront", "walk"],
      priceLevel: "$",
      estimatedDuration: "30-75 minutes",
      bestFor: "Families, walkers, budget-conscious travelers, and anyone needing fresh air.",
      trustSignal: "Central, visible, and simple to add to many downtown itineraries.",
      whyZuriRecommendsIt: "It gives a plan breathing room and keeps the day from becoming only meals and venues.",
      ctaLabel: "Use as an easy stop"
    },
    {
      id: "lauritzen-gardens",
      title: "Lauritzen Gardens",
      country: "United States",
      city: "Omaha",
      area: "South Omaha",
      category: "Outdoor/Nature",
      mood: ["Easy", "Romantic", "Family"],
      shortDescription: "A peaceful botanical garden stop for nature, photos, and slower conversation.",
      longDescription: "Lauritzen Gardens gives the day a calm, scenic rhythm. It is especially useful for a date, family outing, or relaxed morning before heading back toward downtown.",
      tags: ["gardens", "nature", "photos", "peaceful", "date"],
      priceLevel: "$$",
      estimatedDuration: "90-150 minutes",
      bestFor: "Couples, families, and travelers who want a pretty low-stress activity.",
      trustSignal: "Established Omaha attraction with seasonal appeal and clear visitor flow.",
      whyZuriRecommendsIt: "It adds a premium, restorative feel without needing a complicated plan.",
      ctaLabel: "Make this a calm itinerary"
    },
    {
      id: "hollywood-candy",
      title: "Hollywood Candy Browse",
      country: "United States",
      city: "Omaha",
      area: "Old Market",
      category: "Shopping",
      mood: ["Family", "Curious", "Easy"],
      shortDescription: "A playful Old Market stop for candy, vintage finds, and wandering.",
      longDescription: "Hollywood Candy gives an itinerary a little surprise and charm. It is easy to add before dinner, after a museum, or during a family-friendly Old Market loop.",
      tags: ["shopping", "candy", "vintage", "family", "old market"],
      priceLevel: "$",
      estimatedDuration: "20-45 minutes",
      bestFor: "Families, casual dates, and anyone who likes browsing quirky local stops.",
      trustSignal: "Memorable, easy-to-understand stop in Omaha's most visitor-friendly district.",
      whyZuriRecommendsIt: "It turns a basic walk into something more tactile and fun.",
      ctaLabel: "Add a playful stop"
    },
    {
      id: "fontenelle-forest",
      title: "Fontenelle Forest Escape",
      country: "United States",
      city: "Omaha",
      area: "South Omaha",
      category: "Outdoor/Nature",
      mood: ["Active", "Easy", "Family"],
      shortDescription: "Wooded trails and elevated boardwalk moments for a nature-forward Omaha plan.",
      longDescription: "Fontenelle Forest works when you want the trip to feel less urban for a while. Choose it for fresh air, light movement, and a quieter day that still feels intentional.",
      tags: ["hiking", "trails", "forest", "family", "nature"],
      priceLevel: "$$",
      estimatedDuration: "90-180 minutes",
      bestFor: "Active travelers, families, and anyone wanting a nature reset.",
      trustSignal: "A well-known regional nature destination with clear trail options.",
      whyZuriRecommendsIt: "It changes the pace of the trip and balances Omaha's food and culture stops.",
      ctaLabel: "Plan an active day"
    },
    {
      id: "salt-and-spa",
      title: "Midtown Wellness Reset",
      country: "United States",
      city: "Omaha",
      area: "Midtown",
      category: "Wellness",
      mood: ["Easy", "Indulgent", "Romantic"],
      shortDescription: "A spa-style pause for travelers who want the day to feel softer and more restored.",
      longDescription: "Build a wellness reset around a massage, sauna-style session, or calm beauty appointment, then follow it with a light meal or quiet coffee nearby. This is a prototype recommendation category rather than a single booked provider.",
      tags: ["spa", "reset", "self care", "slow day", "wellness"],
      priceLevel: "$$$",
      estimatedDuration: "60-120 minutes",
      bestFor: "Solo travelers, couples, and guests recovering from a packed schedule.",
      trustSignal: "Recommended as a planning pattern; verify provider availability before going.",
      whyZuriRecommendsIt: "It acknowledges that sometimes the best thing to do is lower the pace.",
      ctaLabel: "Ask ZURI for a reset plan"
    },
    {
      id: "kimpton-cottonwood",
      title: "Kimpton Cottonwood Stay-and-Stroll",
      country: "United States",
      city: "Omaha",
      area: "Blackstone",
      category: "Hotels",
      mood: ["Romantic", "Indulgent", "Local"],
      shortDescription: "A polished hotel anchor near Blackstone restaurants, drinks, and Midtown movement.",
      longDescription: "Use the Cottonwood as a base when you want Omaha to feel boutique, walkable in parts, and food-focused. It makes a date night or weekend itinerary feel more premium right away.",
      tags: ["hotel", "boutique", "blackstone", "weekend", "date"],
      priceLevel: "$$$",
      estimatedDuration: "Overnight",
      bestFor: "Couples, weekend travelers, and visitors who want an elevated home base.",
      trustSignal: "Recognizable boutique hotel positioning in a strong dining neighborhood.",
      whyZuriRecommendsIt: "The location makes the rest of the plan easier and more atmospheric.",
      ctaLabel: "Build a stay plan"
    },
    {
      id: "orbt-downtown",
      title: "ORBT Easy Transit Move",
      country: "United States",
      city: "Omaha",
      area: "Downtown",
      category: "Transportation",
      mood: ["Easy", "Local"],
      shortDescription: "Use Omaha's rapid bus line as a simple connector for selected east-west plans.",
      longDescription: "ORBT can help connect parts of an Omaha day without relying fully on rideshare. It is most useful when your stops sit near the route, especially for budget-aware travelers.",
      tags: ["transit", "bus", "budget", "downtown", "car free"],
      priceLevel: "$",
      estimatedDuration: "15-45 minutes",
      bestFor: "Budget travelers, car-free visitors, and simple east-west movement.",
      trustSignal: "Use route and schedule checks before relying on it for time-sensitive plans.",
      whyZuriRecommendsIt: "It gives visitors another movement option and can reduce friction between stops.",
      ctaLabel: "Plan with transit"
    },
    {
      id: "steelhouse-show",
      title: "Steelhouse Omaha Show Night",
      country: "United States",
      city: "Omaha",
      area: "Downtown",
      category: "Events",
      mood: ["Social", "Romantic", "Curious"],
      shortDescription: "A downtown live-event anchor that can turn dinner into a full night out.",
      longDescription: "When there is a show that fits your taste, Steelhouse can make the evening feel planned without adding too many stops. Pair it with an early dinner and one nearby drink after.",
      tags: ["concert", "events", "downtown", "live music", "night out"],
      priceLevel: "$$$",
      estimatedDuration: "2-4 hours",
      bestFor: "Couples, friend groups, and visitors who like a ticketed anchor.",
      trustSignal: "Event-dependent; check the live calendar before committing.",
      whyZuriRecommendsIt: "A scheduled event gives the night shape and makes the rest of the plan easier.",
      ctaLabel: "Build a show-night plan"
    },
    {
      id: "zoo-family-day",
      title: "Henry Doorly Zoo Family Day",
      country: "United States",
      city: "Omaha",
      area: "South Omaha",
      category: "Family Friendly",
      mood: ["Family", "Active", "Curious"],
      shortDescription: "A major Omaha attraction for families and visitors who want a full-day anchor.",
      longDescription: "The zoo can carry most of a day, so the best ZURI plan around it is simple: arrive with energy, add a food break, and keep the evening easy. It is one of Omaha's clearest choices for families.",
      tags: ["zoo", "kids", "family", "animals", "full day"],
      priceLevel: "$$",
      estimatedDuration: "3-6 hours",
      bestFor: "Families, animal lovers, and visitors who want one major attraction.",
      trustSignal: "Widely recognized as one of Omaha's signature attractions.",
      whyZuriRecommendsIt: "It answers the question quickly when kids, mixed ages, or a full-day plan are involved.",
      ctaLabel: "Plan the rest of the day"
    },
    {
      id: "via-farinas-date",
      title: "Via Farina Date Night",
      country: "United States",
      city: "Omaha",
      area: "Little Bohemia",
      category: "Date Night",
      mood: ["Romantic", "Indulgent", "Local"],
      shortDescription: "A warm pasta-centered dinner idea in a neighborhood with a distinctive local feel.",
      longDescription: "Via Farina is a strong prototype pick for a date night because it feels intimate, specific, and easy to build around. Add a pre-dinner drink or a slow walk nearby to make it feel complete.",
      tags: ["pasta", "date", "dinner", "little bohemia", "romantic"],
      priceLevel: "$$$",
      estimatedDuration: "90-150 minutes",
      bestFor: "Couples and travelers looking for a dinner-led plan.",
      trustSignal: "Popular local date-night style recommendation; reservations may matter.",
      whyZuriRecommendsIt: "It gives the evening a clear emotional tone without feeling generic.",
      ctaLabel: "Create a date itinerary"
    },
    {
      id: "inner-rail-aksarben",
      title: "Inner Rail Food Hall",
      country: "United States",
      city: "Omaha",
      area: "Aksarben",
      category: "Food",
      mood: ["Social", "Family", "Easy"],
      shortDescription: "A flexible food-hall option when a group cannot agree on one cuisine.",
      longDescription: "Inner Rail works well for groups, families, and casual meetups because everyone can make a different choice. It pairs naturally with a walk around Aksarben or a nearby event.",
      tags: ["food hall", "group", "aksarben", "casual", "variety"],
      priceLevel: "$$",
      estimatedDuration: "60-90 minutes",
      bestFor: "Groups with mixed preferences, casual meals, and family-friendly plans.",
      trustSignal: "Strong format fit for groups because variety lowers decision friction.",
      whyZuriRecommendsIt: "It solves the practical problem of feeding people with different tastes quickly.",
      ctaLabel: "Use as a group stop"
    },
    {
      id: "dundee-shopping",
      title: "Dundee Neighborhood Browse",
      country: "United States",
      city: "Omaha",
      area: "Dundee",
      category: "Shopping",
      mood: ["Easy", "Local", "Curious"],
      shortDescription: "A gentle local neighborhood loop with shops, cafes, and relaxed meal options.",
      longDescription: "Dundee is a quieter way to experience Omaha. It is good for a slow afternoon, a casual shopping browse, and a meal that feels more neighborhood than downtown.",
      tags: ["neighborhood", "shopping", "cafes", "slow", "local"],
      priceLevel: "$$",
      estimatedDuration: "90-180 minutes",
      bestFor: "Visitors who prefer neighborhoods, browsing, and a calmer pace.",
      trustSignal: "Established Omaha neighborhood with a recognizable local rhythm.",
      whyZuriRecommendsIt: "It broadens the trip beyond the obvious visitor districts.",
      ctaLabel: "Plan a slow afternoon"
    },
    {
      id: "ask-zuri-custom",
      title: "Ask ZURI Custom Plan",
      country: "United States",
      city: "Omaha",
      area: "Downtown",
      category: "Ask ZURI",
      mood: ["Easy", "Curious", "Social", "Romantic", "Family", "Active", "Indulgent", "Local"],
      shortDescription: "Tell ZURI your mood, time, budget, and transport, then get a 3-stop Omaha plan.",
      longDescription: "Use this when the filters are close but you want a smoother answer. ZURI will stitch together a practical route, explain movement and budget, and remind you where live concierge support would improve the plan.",
      tags: ["planner", "custom", "itinerary", "concierge", "fallback"],
      priceLevel: "$$",
      estimatedDuration: "2-4 hours",
      bestFor: "People who want a quick plan instead of browsing every option.",
      trustSignal: "Prototype planner uses the same curated listing set shown on this page.",
      whyZuriRecommendsIt: "It turns discovery into a usable plan and makes the product promise concrete.",
      ctaLabel: "Start Ask ZURI"
    }
  ]
};
