const ZURI_DATA = {
  countries: [
    { id: "us", name: "United States" },
    { id: "rw", name: "Rwanda" }
  ],
  cities: [
    {
      id: "omaha",
      name: "Omaha",
      country: "United States",
      isActive: true,
      tagline: "Friendly neighborhoods, serious food, rich culture, and easygoing days."
    },
    {
      id: "kigali",
      name: "Kigali",
      country: "Rwanda",
      isActive: true,
      tagline: "Clean hills, creative culture, thoughtful hospitality, and easy city movement."
    },
    {
      id: "lincoln",
      name: "Lincoln",
      country: "United States",
      isActive: true,
      tagline: "College-town energy, local food, arts, history, and easygoing Nebraska days."
    },
    {
      id: "rwamagana",
      name: "Rwamagana",
      country: "Rwanda",
      isActive: true,
      tagline: "Eastern Province calm, lakeside movement, local markets, community life, and access to Akagera routes."
    }
  ],
  areas: [
    "Blackstone",
    "Benson",
    "Old Market",
    "Downtown",
    "Midtown",
    "Dundee",
    "Aksarben",
    "Little Bohemia",
    "Riverfront",
    "West Omaha",
    "South Omaha",
    "North Omaha",
    "Haymarket",
    "University District",
    "Downtown Lincoln",
    "Capitol District",
    "Antelope Valley",
    "South Lincoln",
    "Pioneers Park",
    "Holmes Lake",
    "Lincoln Airport",
    "Rwamagana Town",
    "Central Market",
    "Lake Muhazi",
    "Eastern Province",
    "Akagera Gateway",
    "Rwamagana District"
  ],
  categories: [
    "Food",
    "Coffee",
    "Nightlife",
    "Culture",
    "Tours",
    "Outdoor/Nature",
    "Shopping",
    "Wellness",
    "Hotels",
    "Transportation",
    "Events",
    "Family Friendly",
    "Date Night",
    "Ask ZURI"
  ],
  moods: [
    "Easy",
    "Curious",
    "Social",
    "Romantic",
    "Family",
    "Active",
    "Indulgent",
    "Local"
  ],
  listings: [
    {
      id: "old-market-walk",
      title: "Old Market First-Timer Walk",
      country: "United States",
      city: "Omaha",
      area: "Old Market",
      category: "Tours",
      mood: ["Easy", "Curious", "Local"],
      shortDescription: "A low-pressure intro to Omaha with brick streets, galleries, patios, and easy browsing.",
      longDescription: "Start with a slow walk through Old Market, then browse a shop or gallery before choosing a nearby patio, dessert stop, or casual dinner. It works especially well when someone has just arrived and wants the city to feel manageable fast.",
      tags: ["first time", "walkable", "historic", "shops", "patios"],
      priceLevel: "$",
      estimatedDuration: "60-90 minutes",
      bestFor: "Visitors who want the classic Omaha starting point without overplanning.",
      trustSignal: "Reliable first stop because the area is compact, recognizable, and easy to navigate.",
      whyZuriRecommendsIt: "It gives you a quick sense of place and leaves room to pivot into food, shopping, or nightlife.",
      ctaLabel: "Ask ZURI to build around this"
    },
    {
      id: "block-16-lunch",
      title: "Block 16 Lunch Run",
      country: "United States",
      city: "Omaha",
      area: "Downtown",
      category: "Food",
      mood: ["Indulgent", "Local", "Social"],
      shortDescription: "A beloved casual lunch stop for bold sandwiches, fries, and an energetic downtown crowd.",
      longDescription: "Block 16 is a strong pick when you want food that feels distinctly local, satisfying, and unfussy. Pair it with a downtown walk or a stop at the Gene Leahy Mall when the weather cooperates.",
      tags: ["lunch", "casual", "downtown", "sandwiches", "local favorite"],
      priceLevel: "$$",
      estimatedDuration: "45-75 minutes",
      bestFor: "Food-focused visitors, casual dates, and groups that want an Omaha staple.",
      trustSignal: "Commonly recommended by locals and visitors for a memorable casual meal.",
      whyZuriRecommendsIt: "It feels specific to Omaha without requiring a formal reservation or a huge time block.",
      ctaLabel: "Add this to my plan"
    },
    {
      id: "archetype-blackstone",
      title: "Archetype Coffee in Blackstone",
      country: "United States",
      city: "Omaha",
      area: "Blackstone",
      category: "Coffee",
      mood: ["Easy", "Curious", "Local"],
      shortDescription: "A polished coffee stop in one of Omaha's most useful food-and-drink neighborhoods.",
      longDescription: "Use Archetype as a calm reset, a work break, or the first stop before exploring Blackstone's restaurants and bars. It is a simple anchor when your day needs structure but not pressure.",
      tags: ["coffee", "remote work", "blackstone", "morning", "espresso"],
      priceLevel: "$",
      estimatedDuration: "30-60 minutes",
      bestFor: "Solo travelers, remote workers, and coffee people starting a flexible day.",
      trustSignal: "Strong local reputation for quality coffee and a dependable neighborhood location.",
      whyZuriRecommendsIt: "It anchors the day in an area with easy next moves for lunch, dinner, or drinks.",
      ctaLabel: "Plan from here"
    },
    {
      id: "mula-blackstone",
      title: "Mula Tacos and Tequila",
      country: "United States",
      city: "Omaha",
      area: "Blackstone",
      category: "Food",
      mood: ["Social", "Indulgent", "Romantic"],
      shortDescription: "A lively Blackstone pick for tacos, drinks, and an easy group dinner mood.",
      longDescription: "Mula works when the group wants something more animated than a quiet dinner but less complicated than a full night out. It is also well placed for a second stop in Blackstone.",
      tags: ["tacos", "tequila", "group", "dinner", "blackstone"],
      priceLevel: "$$",
      estimatedDuration: "75-120 minutes",
      bestFor: "Groups, casual dates, and visitors who want a social dinner area.",
      trustSignal: "Neighborhood fit is strong because Blackstone has several easy follow-up options.",
      whyZuriRecommendsIt: "It keeps the night flexible and lets you continue nearby without moving across town.",
      ctaLabel: "Build a night around this"
    },
    {
      id: "benson-night-out",
      title: "Benson Night Out",
      country: "United States",
      city: "Omaha",
      area: "Benson",
      category: "Nightlife",
      mood: ["Social", "Local", "Curious"],
      shortDescription: "A casual nightlife circuit with music, drinks, food, and a neighborhood feel.",
      longDescription: "Benson is a good bet when you want a night that can stay loose. Start with dinner, see what music is happening, then choose a bar or late-night bite based on the room's energy.",
      tags: ["bars", "music", "late night", "local", "walkable"],
      priceLevel: "$$",
      estimatedDuration: "2-4 hours",
      bestFor: "People who want a relaxed local night rather than a polished hotel-bar scene.",
      trustSignal: "Known locally as one of Omaha's easiest neighborhoods for a casual night out.",
      whyZuriRecommendsIt: "It offers several choices close together, so the plan can adapt as the night changes.",
      ctaLabel: "Ask ZURI for a Benson route"
    },
    {
      id: "joslyn-arts",
      title: "Joslyn Art Museum Afternoon",
      country: "United States",
      city: "Omaha",
      area: "Midtown",
      category: "Culture",
      mood: ["Curious", "Easy", "Romantic"],
      shortDescription: "A beautiful culture stop for art, architecture, and a quieter Omaha afternoon.",
      longDescription: "Joslyn fits a refined, slower-paced day. It pairs well with coffee before, a Midtown meal after, or a date-night dinner when you want the day to feel considered but not busy.",
      tags: ["museum", "art", "architecture", "quiet", "rainy day"],
      priceLevel: "$",
      estimatedDuration: "90-150 minutes",
      bestFor: "Culture seekers, couples, and visitors needing an indoor anchor.",
      trustSignal: "Major Omaha cultural institution with a strong sense of place.",
      whyZuriRecommendsIt: "It adds depth and beauty to an itinerary without demanding the whole day.",
      ctaLabel: "Pair this with dinner"
    },
    {
      id: "durham-museum",
      title: "The Durham Museum",
      country: "United States",
      city: "Omaha",
      area: "Downtown",
      category: "Culture",
      mood: ["Curious", "Family", "Easy"],
      shortDescription: "Omaha history inside a grand former train station, with exhibits that work for many ages.",
      longDescription: "The Durham Museum is a strong indoor pick for history, architecture, and families. It can stand alone or pair with Old Market before or after because the move between them is simple.",
      tags: ["history", "museum", "family", "indoor", "architecture"],
      priceLevel: "$$",
      estimatedDuration: "90-150 minutes",
      bestFor: "Families, history fans, and visitors seeking an easy indoor activity.",
      trustSignal: "A recognized Omaha landmark with broad appeal across age groups.",
      whyZuriRecommendsIt: "It makes Omaha's story tangible and is easy to combine with downtown plans.",
      ctaLabel: "Add to a family plan"
    },
    {
      id: "gene-leahy-mall",
      title: "Gene Leahy Mall Reset",
      country: "United States",
      city: "Omaha",
      area: "Riverfront",
      category: "Outdoor/Nature",
      mood: ["Easy", "Family", "Active"],
      shortDescription: "A clean, central outdoor pause with green space, public art, and skyline views.",
      longDescription: "Gene Leahy Mall is useful when you want something free, easy, and close to downtown food. It is also a good transition stop between a museum, lunch, and the riverfront.",
      tags: ["park", "free", "downtown", "riverfront", "walk"],
      priceLevel: "$",
      estimatedDuration: "30-75 minutes",
      bestFor: "Families, walkers, budget-conscious travelers, and anyone needing fresh air.",
      trustSignal: "Central, visible, and simple to add to many downtown itineraries.",
      whyZuriRecommendsIt: "It gives a plan breathing room and keeps the day from becoming only meals and venues.",
      ctaLabel: "Use as an easy stop"
    },
    {
      id: "lauritzen-gardens",
      title: "Lauritzen Gardens",
      country: "United States",
      city: "Omaha",
      area: "South Omaha",
      category: "Outdoor/Nature",
      mood: ["Easy", "Romantic", "Family"],
      shortDescription: "A peaceful botanical garden stop for nature, photos, and slower conversation.",
      longDescription: "Lauritzen Gardens gives the day a calm, scenic rhythm. It is especially useful for a date, family outing, or relaxed morning before heading back toward downtown.",
      tags: ["gardens", "nature", "photos", "peaceful", "date"],
      priceLevel: "$$",
      estimatedDuration: "90-150 minutes",
      bestFor: "Couples, families, and travelers who want a pretty low-stress activity.",
      trustSignal: "Established Omaha attraction with seasonal appeal and clear visitor flow.",
      whyZuriRecommendsIt: "It adds a premium, restorative feel without needing a complicated plan.",
      ctaLabel: "Make this a calm itinerary"
    },
    {
      id: "hollywood-candy",
      title: "Hollywood Candy Browse",
      country: "United States",
      city: "Omaha",
      area: "Old Market",
      category: "Shopping",
      mood: ["Family", "Curious", "Easy"],
      shortDescription: "A playful Old Market stop for candy, vintage finds, and wandering.",
      longDescription: "Hollywood Candy gives an itinerary a little surprise and charm. It is easy to add before dinner, after a museum, or during a family-friendly Old Market loop.",
      tags: ["shopping", "candy", "vintage", "family", "old market"],
      priceLevel: "$",
      estimatedDuration: "20-45 minutes",
      bestFor: "Families, casual dates, and anyone who likes browsing quirky local stops.",
      trustSignal: "Memorable, easy-to-understand stop in Omaha's most visitor-friendly district.",
      whyZuriRecommendsIt: "It turns a basic walk into something more tactile and fun.",
      ctaLabel: "Add a playful stop"
    },
    {
      id: "fontenelle-forest",
      title: "Fontenelle Forest Escape",
      country: "United States",
      city: "Omaha",
      area: "South Omaha",
      category: "Outdoor/Nature",
      mood: ["Active", "Easy", "Family"],
      shortDescription: "Wooded trails and elevated boardwalk moments for a nature-forward Omaha plan.",
      longDescription: "Fontenelle Forest works when you want the trip to feel less urban for a while. Choose it for fresh air, light movement, and a quieter day that still feels intentional.",
      tags: ["hiking", "trails", "forest", "family", "nature"],
      priceLevel: "$$",
      estimatedDuration: "90-180 minutes",
      bestFor: "Active travelers, families, and anyone wanting a nature reset.",
      trustSignal: "A well-known regional nature destination with clear trail options.",
      whyZuriRecommendsIt: "It changes the pace of the trip and balances Omaha's food and culture stops.",
      ctaLabel: "Plan an active day"
    },
    {
      id: "salt-and-spa",
      title: "Midtown Wellness Reset",
      country: "United States",
      city: "Omaha",
      area: "Midtown",
      category: "Wellness",
      mood: ["Easy", "Indulgent", "Romantic"],
      shortDescription: "A spa-style pause for travelers who want the day to feel softer and more restored.",
      longDescription: "Build a wellness reset around a massage, sauna-style session, or calm beauty appointment, then follow it with a light meal or quiet coffee nearby. This is a prototype recommendation category rather than a single booked provider.",
      tags: ["spa", "reset", "self care", "slow day", "wellness"],
      priceLevel: "$$$",
      estimatedDuration: "60-120 minutes",
      bestFor: "Solo travelers, couples, and guests recovering from a packed schedule.",
      trustSignal: "Recommended as a planning pattern; verify provider availability before going.",
      whyZuriRecommendsIt: "It acknowledges that sometimes the best thing to do is lower the pace.",
      ctaLabel: "Ask ZURI for a reset plan"
    },
    {
      id: "kimpton-cottonwood",
      title: "Kimpton Cottonwood Stay-and-Stroll",
      country: "United States",
      city: "Omaha",
      area: "Blackstone",
      category: "Hotels",
      mood: ["Romantic", "Indulgent", "Local"],
      shortDescription: "A polished hotel anchor near Blackstone restaurants, drinks, and Midtown movement.",
      longDescription: "Use the Cottonwood as a base when you want Omaha to feel boutique, walkable in parts, and food-focused. It makes a date night or weekend itinerary feel more premium right away.",
      tags: ["hotel", "boutique", "blackstone", "weekend", "date"],
      priceLevel: "$$$",
      estimatedDuration: "Overnight",
      bestFor: "Couples, weekend travelers, and visitors who want an elevated home base.",
      trustSignal: "Recognizable boutique hotel positioning in a strong dining neighborhood.",
      whyZuriRecommendsIt: "The location makes the rest of the plan easier and more atmospheric.",
      ctaLabel: "Build a stay plan"
    },
    {
      id: "orbt-downtown",
      title: "ORBT Easy Transit Move",
      country: "United States",
      city: "Omaha",
      area: "Downtown",
      category: "Transportation",
      mood: ["Easy", "Local"],
      shortDescription: "Use Omaha's rapid bus line as a simple connector for selected east-west plans.",
      longDescription: "ORBT can help connect parts of an Omaha day without relying fully on rideshare. It is most useful when your stops sit near the route, especially for budget-aware travelers.",
      tags: ["transit", "bus", "budget", "downtown", "car free"],
      priceLevel: "$",
      estimatedDuration: "15-45 minutes",
      bestFor: "Budget travelers, car-free visitors, and simple east-west movement.",
      trustSignal: "Use route and schedule checks before relying on it for time-sensitive plans.",
      whyZuriRecommendsIt: "It gives visitors another movement option and can reduce friction between stops.",
      ctaLabel: "Plan with transit"
    },
    {
      id: "steelhouse-show",
      title: "Steelhouse Omaha Show Night",
      country: "United States",
      city: "Omaha",
      area: "Downtown",
      category: "Events",
      mood: ["Social", "Romantic", "Curious"],
      shortDescription: "A downtown live-event anchor that can turn dinner into a full night out.",
      longDescription: "When there is a show that fits your taste, Steelhouse can make the evening feel planned without adding too many stops. Pair it with an early dinner and one nearby drink after.",
      tags: ["concert", "events", "downtown", "live music", "night out"],
      priceLevel: "$$$",
      estimatedDuration: "2-4 hours",
      bestFor: "Couples, friend groups, and visitors who like a ticketed anchor.",
      trustSignal: "Event-dependent; check the live calendar before committing.",
      whyZuriRecommendsIt: "A scheduled event gives the night shape and makes the rest of the plan easier.",
      ctaLabel: "Build a show-night plan"
    },
    {
      id: "zoo-family-day",
      title: "Henry Doorly Zoo Family Day",
      country: "United States",
      city: "Omaha",
      area: "South Omaha",
      category: "Family Friendly",
      mood: ["Family", "Active", "Curious"],
      shortDescription: "A major Omaha attraction for families and visitors who want a full-day anchor.",
      longDescription: "The zoo can carry most of a day, so the best ZURI plan around it is simple: arrive with energy, add a food break, and keep the evening easy. It is one of Omaha's clearest choices for families.",
      tags: ["zoo", "kids", "family", "animals", "full day"],
      priceLevel: "$$",
      estimatedDuration: "3-6 hours",
      bestFor: "Families, animal lovers, and visitors who want one major attraction.",
      trustSignal: "Widely recognized as one of Omaha's signature attractions.",
      whyZuriRecommendsIt: "It answers the question quickly when kids, mixed ages, or a full-day plan are involved.",
      ctaLabel: "Plan the rest of the day"
    },
    {
      id: "via-farinas-date",
      title: "Via Farina Date Night",
      country: "United States",
      city: "Omaha",
      area: "Little Bohemia",
      category: "Date Night",
      mood: ["Romantic", "Indulgent", "Local"],
      shortDescription: "A warm pasta-centered dinner idea in a neighborhood with a distinctive local feel.",
      longDescription: "Via Farina is a strong prototype pick for a date night because it feels intimate, specific, and easy to build around. Add a pre-dinner drink or a slow walk nearby to make it feel complete.",
      tags: ["pasta", "date", "dinner", "little bohemia", "romantic"],
      priceLevel: "$$$",
      estimatedDuration: "90-150 minutes",
      bestFor: "Couples and travelers looking for a dinner-led plan.",
      trustSignal: "Popular local date-night style recommendation; reservations may matter.",
      whyZuriRecommendsIt: "It gives the evening a clear emotional tone without feeling generic.",
      ctaLabel: "Create a date itinerary"
    },
    {
      id: "inner-rail-aksarben",
      title: "Inner Rail Food Hall",
      country: "United States",
      city: "Omaha",
      area: "Aksarben",
      category: "Food",
      mood: ["Social", "Family", "Easy"],
      shortDescription: "A flexible food-hall option when a group cannot agree on one cuisine.",
      longDescription: "Inner Rail works well for groups, families, and casual meetups because everyone can make a different choice. It pairs naturally with a walk around Aksarben or a nearby event.",
      tags: ["food hall", "group", "aksarben", "casual", "variety"],
      priceLevel: "$$",
      estimatedDuration: "60-90 minutes",
      bestFor: "Groups with mixed preferences, casual meals, and family-friendly plans.",
      trustSignal: "Strong format fit for groups because variety lowers decision friction.",
      whyZuriRecommendsIt: "It solves the practical problem of feeding people with different tastes quickly.",
      ctaLabel: "Use as a group stop"
    },
    {
      id: "dundee-shopping",
      title: "Dundee Neighborhood Browse",
      country: "United States",
      city: "Omaha",
      area: "Dundee",
      category: "Shopping",
      mood: ["Easy", "Local", "Curious"],
      shortDescription: "A gentle local neighborhood loop with shops, cafes, and relaxed meal options.",
      longDescription: "Dundee is a quieter way to experience Omaha. It is good for a slow afternoon, a casual shopping browse, and a meal that feels more neighborhood than downtown.",
      tags: ["neighborhood", "shopping", "cafes", "slow", "local"],
      priceLevel: "$$",
      estimatedDuration: "90-180 minutes",
      bestFor: "Visitors who prefer neighborhoods, browsing, and a calmer pace.",
      trustSignal: "Established Omaha neighborhood with a recognizable local rhythm.",
      whyZuriRecommendsIt: "It broadens the trip beyond the obvious visitor districts.",
      ctaLabel: "Plan a slow afternoon"
    },
    {
      id: "ask-zuri-custom",
      title: "Ask ZURI Custom Plan",
      country: "United States",
      city: "Omaha",
      area: "Downtown",
      category: "Ask ZURI",
      mood: ["Easy", "Curious", "Social", "Romantic", "Family", "Active", "Indulgent", "Local"],
      shortDescription: "Tell ZURI your mood, time, budget, and transport, then get a 3-stop Omaha plan.",
      longDescription: "Use this when the filters are close but you want a smoother answer. ZURI will stitch together a practical route, explain movement and budget, and remind you where live concierge support would improve the plan.",
      tags: ["planner", "custom", "itinerary", "concierge", "fallback"],
      priceLevel: "$$",
      estimatedDuration: "2-4 hours",
      bestFor: "People who want a quick plan instead of browsing every option.",
      trustSignal: "Prototype planner uses the same curated listing set shown on this page.",
      whyZuriRecommendsIt: "It turns discovery into a usable plan and makes the product promise concrete.",
      ctaLabel: "Start Ask ZURI"
    },
    {
      id: "kigali-first-timer-route",
      title: "Kigali City First-Timer Route",
      country: "Rwanda",
      city: "Kigali",
      area: "City Centre",
      category: "Tours",
      mood: ["Easy", "Curious", "Local"],
      shortDescription: "A simple orientation route through Kigali's hills, central districts, and practical first stops.",
      longDescription: "Use this as a gentle first pass through Kigali. The route is a prototype planning pattern for getting oriented, understanding distances, and choosing nearby food, culture, or shopping stops without overloading the day.",
      tags: ["first time", "orientation", "city route", "views", "arrival"],
      priceLevel: "$$",
      estimatedDuration: "2-3 hours",
      bestFor: "First-time visitors who want to understand Kigali before choosing a deeper activity.",
      trustSignal: "Prototype route based on well-known Kigali visitor patterns; verify live logistics before going.",
      whyZuriRecommendsIt: "It helps Kigali feel navigable quickly and creates a foundation for the rest of the trip.",
      ctaLabel: "Ask ZURI to build this route"
    },
    {
      id: "kimironko-market-browse",
      title: "Kimironko Market Browse",
      country: "Rwanda",
      city: "Kigali",
      area: "Kimironko",
      category: "Shopping",
      mood: ["Curious", "Local", "Social"],
      shortDescription: "A colorful market browse for textiles, produce, daily-life texture, and locally grounded shopping.",
      longDescription: "Kimironko Market gives visitors a more tactile feel for Kigali. Go with time, patience, and a clear plan for transport; a local guide or trusted driver can make the experience smoother.",
      tags: ["market", "textiles", "shopping", "local", "crafts"],
      priceLevel: "$",
      estimatedDuration: "60-120 minutes",
      bestFor: "Travelers who like markets, textiles, casual browsing, and local atmosphere.",
      trustSignal: "Commonly known Kigali market; prototype users should still confirm timing and comfort level.",
      whyZuriRecommendsIt: "It adds texture and local energy to a Kigali day without needing a formal attraction.",
      ctaLabel: "Add this market stop"
    },
    {
      id: "kigali-genocide-memorial",
      title: "Kigali Genocide Memorial Visit",
      country: "Rwanda",
      city: "Kigali",
      area: "Gisozi",
      category: "Culture",
      mood: ["Curious", "Easy"],
      shortDescription: "A significant memorial and learning stop that should be approached with time and respect.",
      longDescription: "The Kigali Genocide Memorial is an important cultural and historical visit. ZURI treats it as a serious anchor, best paired with a quieter meal or reflective stop rather than a packed schedule.",
      tags: ["history", "memorial", "culture", "reflective", "learning"],
      priceLevel: "$",
      estimatedDuration: "90-150 minutes",
      bestFor: "Visitors seeking historical context and a respectful, reflective experience.",
      trustSignal: "Widely recognized memorial; check current visitor guidance before arrival.",
      whyZuriRecommendsIt: "It gives essential context for understanding Rwanda and should be given enough space in the day.",
      ctaLabel: "Plan a reflective route"
    },
    {
      id: "nyamirambo-neighborhood-walk",
      title: "Nyamirambo Neighborhood Walk",
      country: "Rwanda",
      city: "Kigali",
      area: "Nyamirambo",
      category: "Tours",
      mood: ["Curious", "Local", "Active"],
      shortDescription: "A neighborhood-led walk idea for street life, food, community context, and local rhythm.",
      longDescription: "Nyamirambo is best experienced with local context. This prototype listing points toward a guided or locally supported walk rather than a self-directed checklist.",
      tags: ["neighborhood", "guided walk", "food", "local", "culture"],
      priceLevel: "$$",
      estimatedDuration: "2-3 hours",
      bestFor: "Travelers who want a more social, grounded view of Kigali neighborhoods.",
      trustSignal: "Use a verified local guide or host before turning this into a real booking.",
      whyZuriRecommendsIt: "It brings the city to life through people, streets, and stories rather than just landmarks.",
      ctaLabel: "Ask ZURI for a guided plan"
    },
    {
      id: "question-coffee-stop",
      title: "Question Coffee Stop",
      country: "Rwanda",
      city: "Kigali",
      area: "Kiyovu",
      category: "Coffee",
      mood: ["Easy", "Curious", "Local"],
      shortDescription: "A thoughtful coffee stop for Rwanda's coffee culture, a calm reset, or a morning anchor.",
      longDescription: "Question Coffee is a strong prototype anchor for travelers who want a relaxed introduction to Rwandan coffee. Pair it with a city route, arts visit, or hotel pickup plan.",
      tags: ["coffee", "rwandan coffee", "morning", "quiet", "local"],
      priceLevel: "$",
      estimatedDuration: "30-60 minutes",
      bestFor: "Coffee people, solo travelers, and guests who want a calm first stop.",
      trustSignal: "Recognizable Kigali coffee reference; confirm hours before going.",
      whyZuriRecommendsIt: "It makes the day feel grounded and gives the itinerary a soft, local start.",
      ctaLabel: "Start with coffee"
    },
    {
      id: "kigali-heights-convention-area",
      title: "Kigali Heights / Convention Centre Area",
      country: "Rwanda",
      city: "Kigali",
      area: "Kimihurura",
      category: "Food",
      mood: ["Easy", "Social", "Local"],
      shortDescription: "A polished, practical area for food, meetings, errands, and an easy city reset.",
      longDescription: "The Kigali Heights and Convention Centre area works as a practical anchor when visitors need something central, comfortable, and simple to navigate. It is useful between meetings, hotel check-ins, or evening plans.",
      tags: ["central", "food", "convention centre", "easy", "polished"],
      priceLevel: "$$",
      estimatedDuration: "60-120 minutes",
      bestFor: "Business travelers, first-timers, and guests who want easy logistics.",
      trustSignal: "Area-based prototype recommendation; individual venues should be checked live.",
      whyZuriRecommendsIt: "It reduces friction and gives the day a dependable central base.",
      ctaLabel: "Use as a central stop"
    },
    {
      id: "repub-lounge-dinner-style",
      title: "Repub Lounge-Style Dinner Experience",
      country: "Rwanda",
      city: "Kigali",
      area: "Kimihurura",
      category: "Food",
      mood: ["Social", "Indulgent", "Local"],
      shortDescription: "A warm dinner pattern for Rwandan flavors, conversation, and a relaxed evening mood.",
      longDescription: "This prototype listing points toward a Repub Lounge-style Kigali dinner experience: local flavor, atmosphere, and an evening that can stay relaxed. Verify the exact venue, hours, and table availability before going.",
      tags: ["dinner", "rwandan food", "social", "evening", "kimihurura"],
      priceLevel: "$$",
      estimatedDuration: "90-150 minutes",
      bestFor: "Couples, friends, and visitors who want dinner to anchor the evening.",
      trustSignal: "Prototype recommendation pattern; live venue details require confirmation.",
      whyZuriRecommendsIt: "It gives the evening a clear local food identity without making the plan complicated.",
      ctaLabel: "Build dinner into my plan"
    },
    {
      id: "inema-arts-center-visit",
      title: "Inema Arts Center Visit",
      country: "Rwanda",
      city: "Kigali",
      area: "Kacyiru",
      category: "Culture",
      mood: ["Curious", "Easy", "Local"],
      shortDescription: "A creative arts stop for contemporary Rwandan work, browsing, and cultural context.",
      longDescription: "Inema Arts Center is a strong culture anchor for a Kigali day. It pairs well with coffee, a driver-supported route, or dinner in Kimihurura depending on the mood.",
      tags: ["art", "gallery", "culture", "creative", "local artists"],
      priceLevel: "$",
      estimatedDuration: "60-90 minutes",
      bestFor: "Art lovers, culture seekers, and guests wanting a lighter indoor stop.",
      trustSignal: "Known Kigali arts reference; confirm opening times before visiting.",
      whyZuriRecommendsIt: "It adds creativity and local perspective while staying easy to fit into a half day.",
      ctaLabel: "Add an arts stop"
    },
    {
      id: "mount-kigali-view-plan",
      title: "Mount Kigali / Scenic View Plan",
      country: "Rwanda",
      city: "Kigali",
      area: "Mount Kigali",
      category: "Outdoor/Nature",
      mood: ["Active", "Curious", "Romantic"],
      shortDescription: "A scenic hill-view plan for fresh air, photos, and a wider sense of Kigali's landscape.",
      longDescription: "Use Mount Kigali as a scenic, active counterpoint to food and culture stops. Transport and timing matter, so this works best with a driver-supported plan or a local host.",
      tags: ["views", "hills", "outdoor", "photos", "active"],
      priceLevel: "$$",
      estimatedDuration: "90-180 minutes",
      bestFor: "Active travelers, couples, and visitors who want views over a venue-heavy day.",
      trustSignal: "Prototype scenic route; confirm route, weather, and transport before going.",
      whyZuriRecommendsIt: "Kigali's hills are part of the city's identity, and this makes that visible.",
      ctaLabel: "Plan a scenic route"
    },
    {
      id: "kigali-wellness-reset",
      title: "Kigali Wellness Reset",
      country: "Rwanda",
      city: "Kigali",
      area: "Nyarutarama",
      category: "Wellness",
      mood: ["Easy", "Indulgent", "Romantic"],
      shortDescription: "A slower spa or wellness-style pause for guests who need a restorative city day.",
      longDescription: "This is a prototype planning category for a massage, spa, salon, or quiet wellness pause. A real ZURI concierge would verify providers, availability, and standards before recommending a specific booking.",
      tags: ["spa", "wellness", "reset", "slow day", "self care"],
      priceLevel: "$$$",
      estimatedDuration: "60-120 minutes",
      bestFor: "Travelers recovering from flights, meetings, or a packed itinerary.",
      trustSignal: "Provider verification needed before real-world booking recommendations.",
      whyZuriRecommendsIt: "It respects that a good city experience sometimes means lowering the pace.",
      ctaLabel: "Ask ZURI for a reset plan"
    },
    {
      id: "airport-private-driver-support",
      title: "Airport Pickup / Private Driver Support",
      country: "Rwanda",
      city: "Kigali",
      area: "Kigali International Airport",
      category: "Transportation",
      mood: ["Easy", "Local"],
      shortDescription: "A practical movement option for airport arrival, hotel transfer, or multi-stop city plans.",
      longDescription: "Driver support can make Kigali feel easier, especially for arrivals, evening plans, or routes across several neighborhoods. This is a prototype service concept, not a live booking offer.",
      tags: ["airport", "driver", "transfer", "transport", "arrival"],
      priceLevel: "$$",
      estimatedDuration: "30-90 minutes",
      bestFor: "Arriving guests, business travelers, families, and visitors with luggage or tight timing.",
      trustSignal: "Real driver recommendations require partner vetting and live confirmation.",
      whyZuriRecommendsIt: "Movement is part of the experience; reliable transport can make the whole day smoother.",
      ctaLabel: "Plan with driver support"
    },
    {
      id: "boutique-hotel-stay-base",
      title: "Boutique Hotel Stay Base",
      country: "Rwanda",
      city: "Kigali",
      area: "Kiyovu",
      category: "Hotels",
      mood: ["Easy", "Indulgent", "Romantic"],
      shortDescription: "A stay-base planning idea for travelers who want Kigali to feel calm, polished, and central.",
      longDescription: "This prototype hotel category helps users think about where to anchor the trip. A real version would compare verified hotel partners, location, amenities, and transport fit.",
      tags: ["hotel", "stay", "boutique", "central", "base"],
      priceLevel: "$$$",
      estimatedDuration: "Overnight",
      bestFor: "Couples, business travelers, and guests who want a calmer home base.",
      trustSignal: "Prototype stay concept; live hotel availability and partner status are not checked.",
      whyZuriRecommendsIt: "A good base makes every city movement easier and reduces planning fatigue.",
      ctaLabel: "Build around this stay"
    },
    {
      id: "kigali-nightlife-starter",
      title: "Kigali Nightlife Starter",
      country: "Rwanda",
      city: "Kigali",
      area: "Kimihurura",
      category: "Nightlife",
      mood: ["Social", "Local", "Curious"],
      shortDescription: "A light nightlife starter for drinks, music, and a social evening with flexible movement.",
      longDescription: "Use this as a prototype nightlife pattern rather than a fixed bar crawl. Kigali evenings benefit from current local context, transport planning, and venue checks before committing.",
      tags: ["nightlife", "music", "drinks", "social", "evening"],
      priceLevel: "$$",
      estimatedDuration: "2-4 hours",
      bestFor: "Friends, social travelers, and visitors who want the evening to stay flexible.",
      trustSignal: "Live venue, safety, and transport checks are needed before real-world execution.",
      whyZuriRecommendsIt: "It gives the night shape while leaving room for local guidance.",
      ctaLabel: "Ask ZURI for a night plan"
    },
    {
      id: "local-craft-shopping-stop",
      title: "Local Craft / Shopping Stop",
      country: "Rwanda",
      city: "Kigali",
      area: "Kacyiru",
      category: "Shopping",
      mood: ["Easy", "Curious", "Local"],
      shortDescription: "A thoughtful shopping stop for crafts, gifts, design, and locally made pieces.",
      longDescription: "This prototype listing points toward curated local craft and design shopping. A real ZURI partner layer would verify vendors, quality, and guest fit.",
      tags: ["crafts", "gifts", "design", "shopping", "local makers"],
      priceLevel: "$$",
      estimatedDuration: "45-90 minutes",
      bestFor: "Gift shoppers, design-minded travelers, and guests looking for locally made items.",
      trustSignal: "Vendor verification should happen before any live partner recommendation.",
      whyZuriRecommendsIt: "It helps travelers bring home something more connected to place than a generic souvenir.",
      ctaLabel: "Add a shopping stop"
    },
    {
      id: "kigali-events-pulse",
      title: "Kigali Events Pulse",
      country: "Rwanda",
      city: "Kigali",
      area: "City Centre",
      category: "Events",
      mood: ["Social", "Curious", "Local"],
      shortDescription: "A prototype event-discovery slot for music, culture, conferences, pop-ups, and city happenings.",
      longDescription: "Kigali's event layer should eventually be live and date-aware. For now, this listing marks where ZURI would help guests check what is happening during their stay.",
      tags: ["events", "music", "culture", "pop-up", "calendar"],
      priceLevel: "$$",
      estimatedDuration: "2-4 hours",
      bestFor: "Travelers who prefer a live city moment over a fixed attraction.",
      trustSignal: "Event availability is not live in this prototype and must be checked manually.",
      whyZuriRecommendsIt: "Events can turn a good city visit into a timely, memorable one.",
      ctaLabel: "Ask ZURI what is on"
    },
    {
      id: "ask-zuri-kigali-custom",
      title: "Ask ZURI Kigali Custom Plan",
      country: "Rwanda",
      city: "Kigali",
      area: "City Centre",
      category: "Ask ZURI",
      mood: ["Easy", "Curious", "Social", "Romantic", "Family", "Active", "Indulgent", "Local"],
      shortDescription: "Tell ZURI your mood, budget, time, transport, and area to get a Kigali 3-stop plan.",
      longDescription: "Use this when the Kigali prototype listings are close but you want a smoother answer. ZURI will stitch together a practical route and note where live concierge checks would matter.",
      tags: ["planner", "custom", "itinerary", "concierge", "kigali"],
      priceLevel: "$$",
      estimatedDuration: "2-4 hours",
      bestFor: "Guests who want a quick Kigali plan instead of browsing every option.",
      trustSignal: "Prototype planner uses the same curated Kigali listing set shown on this page.",
      whyZuriRecommendsIt: "It turns Kigali discovery into a usable plan while staying honest about prototype limits.",
      ctaLabel: "Start Ask ZURI Kigali"
    },
    {
      id: "haymarket-first-timer-walk",
      title: "Haymarket First-Timer Walk",
      country: "United States",
      city: "Lincoln",
      area: "Haymarket",
      category: "Tours",
      mood: ["Easy", "Curious", "Local"],
      shortDescription: "A walkable Lincoln intro with brick streets, food, shops, and a friendly downtown rhythm.",
      longDescription: "Start in the Historic Haymarket to get oriented quickly. This prototype route works well before dinner, coffee, a campus loop, or a low-pressure night out.",
      tags: ["first time", "haymarket", "walkable", "historic", "downtown"],
      priceLevel: "$",
      estimatedDuration: "60-90 minutes",
      bestFor: "First-time visitors who want Lincoln to feel easy fast.",
      trustSignal: "Area-based prototype recommendation; verify hours and events before going.",
      whyZuriRecommendsIt: "It gives Lincoln a clear starting point and leaves several easy next moves nearby.",
      ctaLabel: "Build from Haymarket"
    },
    {
      id: "unl-campus-loop",
      title: "University of Nebraska Campus Loop",
      country: "United States",
      city: "Lincoln",
      area: "University District",
      category: "Tours",
      mood: ["Curious", "Active", "Local"],
      shortDescription: "A casual campus loop for college-town energy, landmarks, green space, and local context.",
      longDescription: "Use the University of Nebraska campus as a walkable Lincoln anchor. It pairs naturally with coffee, downtown food, or a museum stop when you want the city to feel connected.",
      tags: ["campus", "university", "walk", "college town", "landmarks"],
      priceLevel: "$",
      estimatedDuration: "60-120 minutes",
      bestFor: "Visitors, students, families, and anyone curious about Lincoln's university energy.",
      trustSignal: "Prototype route based on a central, recognizable Lincoln district.",
      whyZuriRecommendsIt: "The campus explains a lot of Lincoln's pace, identity, and visitor movement.",
      ctaLabel: "Add a campus loop"
    },
    {
      id: "sheldon-museum-art",
      title: "Sheldon Museum of Art Visit",
      country: "United States",
      city: "Lincoln",
      area: "University District",
      category: "Culture",
      mood: ["Curious", "Easy", "Romantic"],
      shortDescription: "A polished arts stop on campus for a calmer, culture-forward Lincoln plan.",
      longDescription: "Sheldon Museum of Art can anchor a thoughtful afternoon without making the day too busy. Pair it with campus walking, coffee, or dinner in Haymarket.",
      tags: ["art", "museum", "campus", "indoor", "culture"],
      priceLevel: "$",
      estimatedDuration: "60-90 minutes",
      bestFor: "Art lovers, couples, solo travelers, and rainy-day plans.",
      trustSignal: "Recognized Lincoln arts institution; confirm hours before visiting.",
      whyZuriRecommendsIt: "It adds depth and calm to a city day while staying easy to reach.",
      ctaLabel: "Pair with coffee"
    },
    {
      id: "nebraska-state-capitol-stop",
      title: "Nebraska State Capitol Stop",
      country: "United States",
      city: "Lincoln",
      area: "Capitol District",
      category: "Culture",
      mood: ["Curious", "Easy", "Local"],
      shortDescription: "A landmark stop for architecture, Nebraska civic history, and a clear sense of place.",
      longDescription: "The Nebraska State Capitol is a useful Lincoln anchor when visitors want history and architecture without needing a full-day attraction. Check visitor guidance before going.",
      tags: ["capitol", "history", "architecture", "landmark", "nebraska"],
      priceLevel: "$",
      estimatedDuration: "45-90 minutes",
      bestFor: "History fans, architecture people, and first-time Lincoln visitors.",
      trustSignal: "Major Lincoln landmark; public access details should be checked live.",
      whyZuriRecommendsIt: "It gives Lincoln civic context and pairs well with downtown food or campus stops.",
      ctaLabel: "Add a landmark stop"
    },
    {
      id: "mill-coffee-reset",
      title: "The Mill Coffee Reset",
      country: "United States",
      city: "Lincoln",
      area: "Haymarket",
      category: "Coffee",
      mood: ["Easy", "Local", "Curious"],
      shortDescription: "A dependable coffee reset for starting, pausing, or re-centering a Lincoln day.",
      longDescription: "Use a Mill-style coffee stop as a flexible anchor before exploring Haymarket, campus, or downtown. This is a prototype planning recommendation; verify exact location and hours.",
      tags: ["coffee", "haymarket", "morning", "reset", "local"],
      priceLevel: "$",
      estimatedDuration: "30-60 minutes",
      bestFor: "Solo travelers, remote workers, coffee people, and low-pressure meetups.",
      trustSignal: "Recognizable Lincoln coffee reference; check hours before going.",
      whyZuriRecommendsIt: "A good coffee stop makes the rest of the city easier to decide.",
      ctaLabel: "Start with coffee"
    },
    {
      id: "lincoln-childrens-zoo-family-day",
      title: "Lincoln Children's Zoo Family Day",
      country: "United States",
      city: "Lincoln",
      area: "Antelope Valley",
      category: "Family Friendly",
      mood: ["Family", "Active", "Easy"],
      shortDescription: "A family-friendly anchor that can carry a morning or afternoon with kids.",
      longDescription: "The zoo is a clear choice when the group includes children or mixed ages. Keep the rest of the day simple with food, rest, or an easy outdoor stop.",
      tags: ["kids", "zoo", "family", "animals", "easy"],
      priceLevel: "$$",
      estimatedDuration: "2-4 hours",
      bestFor: "Families and visitors planning around kids' energy.",
      trustSignal: "Established Lincoln family attraction; confirm seasonal hours and tickets.",
      whyZuriRecommendsIt: "It answers the family-day question quickly and reduces planning friction.",
      ctaLabel: "Plan a family day"
    },
    {
      id: "pioneers-park-nature-reset",
      title: "Pioneers Park Nature Reset",
      country: "United States",
      city: "Lincoln",
      area: "Pioneers Park",
      category: "Outdoor/Nature",
      mood: ["Active", "Easy", "Family"],
      shortDescription: "A bigger outdoor reset with trails, prairie feel, and room to slow down.",
      longDescription: "Pioneers Park is useful when the day needs air, space, and a break from downtown. It works best with driving or rideshare support.",
      tags: ["park", "trails", "nature", "prairie", "family"],
      priceLevel: "$",
      estimatedDuration: "90-180 minutes",
      bestFor: "Active travelers, families, and anyone who wants a nature-forward Lincoln plan.",
      trustSignal: "Prototype outdoor recommendation; check weather and route before going.",
      whyZuriRecommendsIt: "It balances Lincoln's campus and downtown energy with space and quiet.",
      ctaLabel: "Plan a nature reset"
    },
    {
      id: "holmes-lake-outdoor-plan",
      title: "Holmes Lake Easy Outdoor Plan",
      country: "United States",
      city: "Lincoln",
      area: "Holmes Lake",
      category: "Outdoor/Nature",
      mood: ["Easy", "Active", "Romantic"],
      shortDescription: "A relaxed lake-area plan for walking, fresh air, photos, and a softer pace.",
      longDescription: "Holmes Lake gives Lincoln visitors an easy outdoor option when they want movement without a full hiking plan. Pair it with coffee or a casual meal.",
      tags: ["lake", "walk", "outdoor", "photos", "easy"],
      priceLevel: "$",
      estimatedDuration: "45-120 minutes",
      bestFor: "Couples, walkers, families, and guests who want a simple outdoor break.",
      trustSignal: "Area-based prototype recommendation; check weather before going.",
      whyZuriRecommendsIt: "It makes a Lincoln day feel calmer and less venue-heavy.",
      ctaLabel: "Add an easy outdoor stop"
    },
    {
      id: "downtown-lincoln-dinner-starter",
      title: "Downtown Lincoln Dinner Starter",
      country: "United States",
      city: "Lincoln",
      area: "Downtown Lincoln",
      category: "Food",
      mood: ["Social", "Indulgent", "Local"],
      shortDescription: "A flexible dinner zone for choosing a local meal before a walk, show, or night out.",
      longDescription: "Use downtown Lincoln as a dinner starting point when you want options without overcommitting. A live version of ZURI would verify venue hours and availability.",
      tags: ["dinner", "downtown", "local food", "group", "evening"],
      priceLevel: "$$",
      estimatedDuration: "75-120 minutes",
      bestFor: "Groups, couples, and visitors who want dinner to anchor the evening.",
      trustSignal: "Prototype area recommendation; individual venue details should be checked live.",
      whyZuriRecommendsIt: "It creates a simple evening structure with easy follow-up options.",
      ctaLabel: "Build dinner into my plan"
    },
    {
      id: "lincoln-nightlife-music-starter",
      title: "Lincoln Nightlife / Music Starter",
      country: "United States",
      city: "Lincoln",
      area: "Downtown Lincoln",
      category: "Nightlife",
      mood: ["Social", "Local", "Curious"],
      shortDescription: "A light nightlife pattern for live music, drinks, and a flexible Lincoln evening.",
      longDescription: "Lincoln's nightlife is best treated as a current-events check. This prototype card marks where ZURI would help match dinner, music, and movement.",
      tags: ["nightlife", "music", "drinks", "downtown", "evening"],
      priceLevel: "$$",
      estimatedDuration: "2-4 hours",
      bestFor: "Friends, social travelers, and visitors looking for a casual night out.",
      trustSignal: "Live event and venue checks are needed before making a real plan.",
      whyZuriRecommendsIt: "It gives the evening shape while staying flexible.",
      ctaLabel: "Ask ZURI for a night plan"
    },
    {
      id: "lincoln-boutique-stay-base",
      title: "Boutique Stay Base",
      country: "United States",
      city: "Lincoln",
      area: "Haymarket",
      category: "Hotels",
      mood: ["Easy", "Indulgent", "Romantic"],
      shortDescription: "A stay-base planning idea for guests who want easy access to Haymarket and downtown.",
      longDescription: "This prototype hotel category helps guests think about where to anchor a Lincoln visit. Real recommendations would require verified partners and live availability.",
      tags: ["hotel", "stay", "haymarket", "base", "weekend"],
      priceLevel: "$$$",
      estimatedDuration: "Overnight",
      bestFor: "Weekend travelers, couples, and visitors who want a walkable base.",
      trustSignal: "Prototype stay concept; no live booking or availability is checked.",
      whyZuriRecommendsIt: "A good base makes Lincoln easier to experience without constant replanning.",
      ctaLabel: "Build around this stay"
    },
    {
      id: "ask-zuri-lincoln-custom",
      title: "Ask ZURI Lincoln Custom Plan",
      country: "United States",
      city: "Lincoln",
      area: "Downtown Lincoln",
      category: "Ask ZURI",
      mood: ["Easy", "Curious", "Social", "Romantic", "Family", "Active", "Indulgent", "Local"],
      shortDescription: "Tell ZURI your mood, budget, time, transport, and area to get a Lincoln 3-stop plan.",
      longDescription: "Use this when you want a smoother Lincoln answer from the prototype set. ZURI stitches together practical stops and notes where live checks would matter.",
      tags: ["planner", "custom", "itinerary", "concierge", "lincoln"],
      priceLevel: "$$",
      estimatedDuration: "2-4 hours",
      bestFor: "Guests who want a quick Lincoln plan instead of browsing every option.",
      trustSignal: "Prototype planner uses the same curated Lincoln listing set shown on this page.",
      whyZuriRecommendsIt: "It turns Lincoln discovery into a usable plan while staying honest about prototype limits.",
      ctaLabel: "Start Ask ZURI Lincoln"
    },
    {
      id: "rwamagana-first-timer-route",
      title: "Rwamagana Town First-Timer Route",
      country: "Rwanda",
      city: "Rwamagana",
      area: "Rwamagana Town",
      category: "Tours",
      mood: ["Easy", "Curious", "Local"],
      shortDescription: "A gentle town orientation route for understanding Rwamagana's pace, streets, and local movement.",
      longDescription: "Use this as a first pass through Rwamagana, especially if arriving from Kigali or heading east. This is prototype guidance, not a guided booking.",
      tags: ["first time", "town route", "orientation", "local", "arrival"],
      priceLevel: "$",
      estimatedDuration: "60-90 minutes",
      bestFor: "Visitors who want a simple, low-pressure start in Rwamagana.",
      trustSignal: "Prototype route; local conditions and transport should be confirmed before going.",
      whyZuriRecommendsIt: "It helps the town feel legible before adding markets, food, or lake movement.",
      ctaLabel: "Build a town route"
    },
    {
      id: "rwamagana-local-market-browse",
      title: "Local Market Browse",
      country: "Rwanda",
      city: "Rwamagana",
      area: "Central Market",
      category: "Shopping",
      mood: ["Curious", "Local", "Social"],
      shortDescription: "A local market browse for produce, daily-life texture, simple shopping, and town energy.",
      longDescription: "This prototype market stop should be approached with time, respect, and local context. A live ZURI version would verify timing and comfort level.",
      tags: ["market", "shopping", "local life", "produce", "browse"],
      priceLevel: "$",
      estimatedDuration: "45-90 minutes",
      bestFor: "Travelers who enjoy markets and grounded local atmosphere.",
      trustSignal: "Prototype market recommendation; verify timing and local guidance.",
      whyZuriRecommendsIt: "Markets make a place feel real and give visitors a useful sense of daily rhythm.",
      ctaLabel: "Add a market stop"
    },
    {
      id: "lake-muhazi-easy-day-plan",
      title: "Lake Muhazi Easy Day Plan",
      country: "Rwanda",
      city: "Rwamagana",
      area: "Lake Muhazi",
      category: "Outdoor/Nature",
      mood: ["Easy", "Romantic", "Family"],
      shortDescription: "A lakeside plan for slower movement, views, conversation, and an Eastern Province reset.",
      longDescription: "Lake Muhazi gives Rwamagana a calming outdoor anchor. Transport, weather, and exact access points should be checked before turning this into a real itinerary.",
      tags: ["lake", "lakeside", "relax", "views", "family"],
      priceLevel: "$$",
      estimatedDuration: "2-4 hours",
      bestFor: "Couples, families, and travelers who want a slower lakeside day.",
      trustSignal: "Prototype area recommendation; access and venue details need live confirmation.",
      whyZuriRecommendsIt: "The lake adds a distinctive sense of place and a softer pace to the route.",
      ctaLabel: "Plan a lakeside day"
    },
    {
      id: "eastern-province-coffee-tea-stop",
      title: "Eastern Province Coffee / Tea Stop",
      country: "Rwanda",
      city: "Rwamagana",
      area: "Rwamagana Town",
      category: "Coffee",
      mood: ["Easy", "Local", "Curious"],
      shortDescription: "A simple coffee or tea pause for resetting, meeting, or starting a Rwamagana plan.",
      longDescription: "This prototype listing marks a calm beverage stop rather than a specific verified vendor. A live version would confirm the best local option for the day.",
      tags: ["coffee", "tea", "pause", "local", "easy"],
      priceLevel: "$",
      estimatedDuration: "30-60 minutes",
      bestFor: "Travelers who need a calm anchor between town, market, and lake movement.",
      trustSignal: "Provider verification is needed before a live vendor recommendation.",
      whyZuriRecommendsIt: "A small reset can make a regional day feel easier and better paced.",
      ctaLabel: "Start with a pause"
    },
    {
      id: "rwamagana-community-culture-walk",
      title: "Community Culture Walk",
      country: "Rwanda",
      city: "Rwamagana",
      area: "Rwamagana District",
      category: "Culture",
      mood: ["Curious", "Local", "Active"],
      shortDescription: "A locally supported walk concept for community context, daily life, and respectful learning.",
      longDescription: "This should be locally guided or hosted before becoming a real guest experience. In prototype form, it marks ZURI's future role in connecting visitors with respectful community context.",
      tags: ["community", "culture", "walk", "local host", "learning"],
      priceLevel: "$$",
      estimatedDuration: "90-150 minutes",
      bestFor: "Visitors who want context and connection rather than a checklist.",
      trustSignal: "Requires local host verification before any real-world recommendation.",
      whyZuriRecommendsIt: "It makes the city layer human-backed and grounded in place.",
      ctaLabel: "Ask ZURI for a hosted route"
    },
    {
      id: "akagera-gateway-transport-support",
      title: "Akagera Gateway Transport Support",
      country: "Rwanda",
      city: "Rwamagana",
      area: "Akagera Gateway",
      category: "Transportation",
      mood: ["Easy", "Active", "Curious"],
      shortDescription: "A planning concept for driver-supported movement toward Akagera routes from Rwamagana.",
      longDescription: "Rwamagana can be part of an eastern movement plan toward Akagera. This prototype card does not book transport; it marks where vetted driver support would matter.",
      tags: ["akagera", "driver", "transport", "day trip", "eastern route"],
      priceLevel: "$$$",
      estimatedDuration: "Half day",
      bestFor: "Travelers planning regional movement, day trips, or onward routes.",
      trustSignal: "Driver and route verification are required before live use.",
      whyZuriRecommendsIt: "Transport is the difference between an idea and a usable regional day.",
      ctaLabel: "Plan with driver support"
    },
    {
      id: "rwamagana-local-food-starter",
      title: "Local Food Starter",
      country: "Rwanda",
      city: "Rwamagana",
      area: "Rwamagana Town",
      category: "Food",
      mood: ["Local", "Social", "Easy"],
      shortDescription: "A prototype food stop for a simple local meal and a grounded town plan.",
      longDescription: "Use this as a placeholder for a verified local food partner in a future ZURI version. For now, it helps the itinerary include a practical meal anchor.",
      tags: ["food", "local meal", "town", "lunch", "casual"],
      priceLevel: "$",
      estimatedDuration: "45-90 minutes",
      bestFor: "Visitors who want the day to include a simple, local meal.",
      trustSignal: "Specific restaurant or vendor details should be verified before recommendation.",
      whyZuriRecommendsIt: "A local meal gives the route structure and keeps the plan from becoming only movement.",
      ctaLabel: "Add a food stop"
    },
    {
      id: "rwamagana-guesthouse-stay-base",
      title: "Guesthouse Stay Base",
      country: "Rwanda",
      city: "Rwamagana",
      area: "Rwamagana Town",
      category: "Hotels",
      mood: ["Easy", "Local", "Indulgent"],
      shortDescription: "A stay-base planning idea for travelers who want a quieter Eastern Province overnight.",
      longDescription: "This prototype stay category helps guests think about where to anchor a regional visit. Live ZURI would verify guesthouses, amenities, location, and availability.",
      tags: ["guesthouse", "stay", "overnight", "base", "regional"],
      priceLevel: "$$",
      estimatedDuration: "Overnight",
      bestFor: "Travelers building a calmer overnight or regional movement plan.",
      trustSignal: "No live availability or partner verification is included in this prototype.",
      whyZuriRecommendsIt: "A good base makes regional exploration easier and less rushed.",
      ctaLabel: "Build around this stay"
    },
    {
      id: "rwamagana-lakeside-relaxation",
      title: "Lakeside Relaxation Plan",
      country: "Rwanda",
      city: "Rwamagana",
      area: "Lake Muhazi",
      category: "Wellness",
      mood: ["Easy", "Romantic", "Indulgent"],
      shortDescription: "A slower lakeside reset for rest, conversation, and a softer Rwamagana day.",
      longDescription: "This wellness-style prototype uses Lake Muhazi as a calming anchor. Real recommendations would need verified access, providers, and transport.",
      tags: ["lake", "wellness", "relax", "slow day", "reset"],
      priceLevel: "$$",
      estimatedDuration: "2-4 hours",
      bestFor: "Couples, solo travelers, and guests who want a restorative route.",
      trustSignal: "Access and provider details must be confirmed before real use.",
      whyZuriRecommendsIt: "It recognizes that the best regional plan may be slower and quieter.",
      ctaLabel: "Create a lakeside reset"
    },
    {
      id: "rwamagana-day-trip-driver-support",
      title: "Private Driver / Day Trip Support",
      country: "Rwanda",
      city: "Rwamagana",
      area: "Eastern Province",
      category: "Transportation",
      mood: ["Easy", "Family", "Active"],
      shortDescription: "A practical support layer for town, lake, and regional day-trip movement.",
      longDescription: "Driver support can make Rwamagana easier for visitors, especially with lake stops or onward plans. This is a prototype service concept, not a live booking offer.",
      tags: ["driver", "day trip", "transport", "family", "regional"],
      priceLevel: "$$",
      estimatedDuration: "2-6 hours",
      bestFor: "Families, arriving guests, regional travelers, and anyone with tight timing.",
      trustSignal: "Real driver recommendations require partner vetting and live confirmation.",
      whyZuriRecommendsIt: "Reliable movement is central to making the regional experience usable.",
      ctaLabel: "Plan with transport support"
    },
    {
      id: "rwamagana-community-event-check",
      title: "Rwamagana Community Event Check",
      country: "Rwanda",
      city: "Rwamagana",
      area: "Rwamagana Town",
      category: "Events",
      mood: ["Curious", "Social", "Local"],
      shortDescription: "A prototype prompt to look for local gatherings, sports, church-adjacent events, or community moments before you go.",
      longDescription: "This listing does not claim live event access. It shows how ZURI could help guests ask the right local questions and verify whether something appropriate is happening during their visit.",
      tags: ["events", "community", "local", "calendar", "prototype"],
      priceLevel: "$",
      estimatedDuration: "1-3 hours",
      bestFor: "Guests who want local context without assuming a fixed tourist schedule.",
      trustSignal: "Live events would need same-day local confirmation before recommendation.",
      whyZuriRecommendsIt: "Events can make a regional visit feel more connected when they are verified and respectful.",
      ctaLabel: "Ask about local events"
    },
    {
      id: "rwamagana-low-key-evening-starter",
      title: "Rwamagana Low-Key Evening Starter",
      country: "Rwanda",
      city: "Rwamagana",
      area: "Rwamagana Town",
      category: "Nightlife",
      mood: ["Social", "Easy", "Local"],
      shortDescription: "A gentle evening-plan concept for food, conversation, and a verified local stop rather than heavy nightlife claims.",
      longDescription: "This prototype keeps the evening language careful. A live ZURI version would verify current venues, safety, hours, transport, and fit before sending a guest out at night.",
      tags: ["evening", "nightlife", "social", "food", "local"],
      priceLevel: "$$",
      estimatedDuration: "2-3 hours",
      bestFor: "Travelers who want a simple, lower-pressure evening in town.",
      trustSignal: "No venue hours, availability, or safety checks are live in this prototype.",
      whyZuriRecommendsIt: "Some guests need an evening option, but it should be handled with care and local verification.",
      ctaLabel: "Shape an evening plan"
    },
    {
      id: "ask-zuri-rwamagana-custom",
      title: "Ask ZURI Rwamagana Custom Plan",
      country: "Rwanda",
      city: "Rwamagana",
      area: "Rwamagana Town",
      category: "Ask ZURI",
      mood: ["Easy", "Curious", "Social", "Romantic", "Family", "Active", "Indulgent", "Local"],
      shortDescription: "Tell ZURI your mood, budget, time, transport, and area to get a Rwamagana 3-stop plan.",
      longDescription: "Use this when you want a smoother Rwamagana answer from the prototype set. ZURI will stitch together practical stops and note where live checks would matter.",
      tags: ["planner", "custom", "itinerary", "concierge", "rwamagana"],
      priceLevel: "$$",
      estimatedDuration: "2-4 hours",
      bestFor: "Guests who want a quick Rwamagana plan instead of browsing every option.",
      trustSignal: "Prototype planner uses the same curated Rwamagana listing set shown on this page.",
      whyZuriRecommendsIt: "It turns Rwamagana discovery into a usable plan while staying honest about prototype limits.",
      ctaLabel: "Start Ask ZURI Rwamagana"
    }
  ]
};
